import { useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { api } from '../../lib/api.js';
import { Card } from '../../components/ui/card.jsx';
import { Badge } from '../../components/ui/badge.jsx';
import { Button } from '../../components/ui/button.jsx';
import { Input } from '../../components/ui/input.jsx';
import { Label } from '../../components/ui/label.jsx';
import { Select } from '../../components/ui/select.jsx';
import { PageHeader, EmptyState } from '../../components/ui/page.jsx';
import { useCycle } from '../../cycles/CycleContext.jsx';

const today = new Date().toISOString().slice(0, 10);
const STEPS = [['1', 'Cycle details'], ['2', 'Build roster'], ['3', 'Required documents']];

function statusLabel(status) { return status === 'not_started' ? 'Draft' : status === 'open' ? 'Open' : 'Closed'; }
function downloadCredentials(credentials) {
  const csv = ['email,temporary_password', ...credentials.map((row) => `${row.email},${row.temporary_password}`)].join('\n');
  const link = document.createElement('a');
  link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' }));
  link.download = 'new-cycle-account-credentials.csv';
  link.click();
  URL.revokeObjectURL(link.href);
}
function CycleBulkImport({ departmentId, onComplete }) {
  const [file, setFile] = useState(null);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [busy, setBusy] = useState(false);
  const template = () => {
    const csv = ['email,full_name,phone,role,roll_number,batch_year,mentorship_scope', 'asha@university.edu,Asha Kumar,9876543210,student,CSE2027001,2027,', 'ravi@university.edu,Ravi Mentor,,faculty,,,research'].join('\n');
    const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'cycle-people-template.csv'; link.click(); URL.revokeObjectURL(link.href);
  };
  async function submit(event) {
    event.preventDefault(); if (!file || !departmentId) return;
    setBusy(true); setError(null);
    try { const body = new FormData(); body.append('file', file); body.append('default_department_id', departmentId); body.append('generate_credentials', 'true'); const data = await api('/admin/users/bulk', { method: 'POST', body, isFormData: true }); setResult(data); onComplete(data.results); }
    catch (failure) { setError(failure.message); } finally { setBusy(false); }
  }
  return <div className="mt-5 rounded-xl border border-slate-200 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold text-slate-950">Upload a department list</h3><p className="mt-1 text-sm text-slate-600">Passwords are generated for new accounts and downloadable once after import.</p></div><Button type="button" variant="secondary" onClick={template}>Download template</Button></div><form className="mt-4" onSubmit={submit}><input type="file" accept=".csv,text/csv,.xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" className="block w-full rounded-lg border border-dashed border-slate-300 bg-slate-50 p-3 text-sm" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><p className="mt-2 text-xs text-slate-500">The department selected above is applied to every row. Include only students and faculty.</p><Button className="mt-4" disabled={!file || busy}>{busy ? 'Creating accounts…' : 'Import and add to roster'}</Button></form>{error && <p className="mt-3 text-sm text-red-700">{error}</p>}{result && <div className="mt-4 rounded-lg bg-slate-50 p-3 text-sm"><p className="font-semibold">{result.results.filter((row) => row.ok).length} accounts created · {result.results.filter((row) => !row.ok).length} need attention</p>{result.credentials?.length ? <Button className="mt-3" variant="secondary" onClick={() => downloadCredentials(result.credentials)}>Download temporary passwords</Button> : null}</div>}</div>;
}
function CycleSinglePerson({ departmentId, onComplete }) {
  const [form, setForm] = useState({ full_name: '', email: '', password: '', role: 'student', roll_number: '', phone: '', mentorship_scope: 'research' });
  const create = useMutation({ mutationFn: () => api('/admin/users', { method: 'POST', body: { email: form.email, password: form.password, full_name: form.full_name, phone: form.phone || undefined, roll_number: form.role === 'student' ? form.roll_number || undefined : undefined, mentorship_scope: form.role === 'faculty' ? form.mentorship_scope : undefined, roles: [{ role: form.role, department_id: departmentId }] } }), onSuccess: (user) => { onComplete(user); setForm({ full_name: '', email: '', password: '', role: 'student', roll_number: '', phone: '', mentorship_scope: 'research' }); } });
  return <form className="mt-5 rounded-xl border border-slate-200 p-5" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><h3 className="font-bold text-slate-950">Create one account</h3><div className="mt-4 grid gap-3 sm:grid-cols-2"><div><Label>Full name</Label><Input value={form.full_name} required onChange={(event) => setForm({ ...form, full_name: event.target.value })} /></div><div><Label>Email</Label><Input type="email" value={form.email} required onChange={(event) => setForm({ ...form, email: event.target.value })} /></div><div><Label>Temporary password</Label><Input type="password" minLength={8} value={form.password} required onChange={(event) => setForm({ ...form, password: event.target.value })} /></div><div><Label>Role</Label><Select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })}><option value="student">Student</option><option value="faculty">Faculty</option></Select></div></div>{form.role === 'student' && <div className="mt-3"><Label>Roll number <span className="font-normal text-slate-400">(optional)</span></Label><Input value={form.roll_number} onChange={(event) => setForm({ ...form, roll_number: event.target.value })} /></div>}{form.role === 'faculty' && <div className="mt-3"><Label>Faculty workspace</Label><Select value={form.mentorship_scope} onChange={(event) => setForm({ ...form, mentorship_scope: event.target.value })}><option value="research">Research mentor</option><option value="crcs_self">CRCS/self-internship mentor</option></Select></div>}<Button className="mt-4" disabled={create.isPending}>{create.isPending ? 'Creating…' : 'Create and add to roster'}</Button>{create.isError && <p className="mt-2 text-sm text-red-700">{create.error.message}</p>}</form>;
}
function RequiredDocuments({ cycleId, isDraft, documents }) {
  const queryClient = useQueryClient();
  const [file, setFile] = useState(null); const [title, setTitle] = useState(''); const [required, setRequired] = useState(true);
  const progress = useQuery({ queryKey: ['cycle-document-progress', cycleId], queryFn: () => api(`/cycle-documents/${cycleId}/progress`), enabled: !!cycleId });
  const upload = useMutation({ mutationFn: () => { const body = new FormData(); body.append('file', file); body.append('title', title); body.append('is_required', String(required)); return api(`/cycle-documents/${cycleId}`, { method: 'POST', body, isFormData: true }); }, onSuccess: () => { setFile(null); setTitle(''); queryClient.invalidateQueries({ queryKey: ['cycle-documents', cycleId] }); queryClient.invalidateQueries({ queryKey: ['cycle-document-progress', cycleId] }); } });
  return <div className="mt-5"><div className="rounded-xl bg-slate-50 p-4"><p className="font-semibold text-slate-900">Required acknowledgement</p><p className="mt-1 text-sm text-slate-600">Each cycle user must explicitly agree to required PDFs before opening their dashboard. Uploading a new version requires acknowledgement again.</p></div>{isDraft && <form className="mt-4 rounded-xl border border-slate-200 p-5" onSubmit={(event) => { event.preventDefault(); upload.mutate(); }}><h3 className="font-bold">Add a PDF</h3><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_1.2fr]"><div><Label>Document title</Label><Input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Internship handbook" required /></div><div><Label>PDF file</Label><input type="file" accept="application/pdf,.pdf" onChange={(event) => setFile(event.target.files?.[0] ?? null)} className="mt-1 block w-full rounded-lg border border-dashed border-slate-300 bg-slate-50 p-2 text-sm" required /></div></div><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={required} onChange={(event) => setRequired(event.target.checked)} /> Require acknowledgement before dashboard access</label><Button className="mt-4" disabled={!file || !title.trim() || upload.isPending}>{upload.isPending ? 'Uploading…' : 'Upload document'}</Button>{upload.isError && <p className="mt-2 text-sm text-red-700">{upload.error.message}</p>}</form>}<div className="mt-4 space-y-2">{documents?.length ? documents.map((document) => <div key={document.id} className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-200 px-4 py-3"><span><span className="block font-semibold">{document.title}</span><span className="text-xs text-slate-500">{document.file_name} · Version {document.version} · {document.is_required ? 'Required' : 'Optional'}</span></span><a href={document.url} target="_blank" rel="noreferrer" className="text-sm font-bold text-indigo-700">Open PDF</a></div>) : <p className="rounded-lg border border-dashed border-slate-300 p-4 text-sm text-slate-500">No documents uploaded yet.</p>}</div>{progress.data?.documents?.length ? <div className="mt-4 rounded-lg bg-slate-50 p-3 text-sm"><p className="font-semibold">Acknowledgement progress</p>{progress.data.documents.map((document) => <p key={document.id} className="mt-1 text-slate-600">{document.title}: {document.acknowledgement_count} / {progress.data.participant_count} people agreed</p>)}</div> : null}</div>;
}
function Stepper({ step, onStep }) { return <ol className="mb-6 grid gap-2 md:grid-cols-3">{STEPS.map(([number, title]) => { const active = Number(number) === step; return <li key={number}><button type="button" disabled={Number(number) > step} onClick={() => onStep(Number(number))} className={`flex w-full items-center gap-3 rounded-xl border p-3 text-left ${active ? 'border-indigo-500 bg-indigo-50 ring-2 ring-indigo-100' : Number(number) < step ? 'border-slate-200 bg-white' : 'border-slate-100 bg-slate-50 text-slate-400'}`}><span className={`grid h-7 w-7 place-items-center rounded-full text-sm font-bold ${active ? 'bg-indigo-600 text-white' : 'bg-slate-200 text-slate-600'}`}>{number}</span><span className="font-bold">{title}</span></button></li>; })}</ol>; }

export default function CycleSetupPage() {
  const queryClient = useQueryClient(); const { cycles, selectCycle, selectedCycle: activeCycle } = useCycle();
  const [step, setStep] = useState(1); const [cycleId, setCycleId] = useState(null); const [draft, setDraft] = useState({ name: '', batch_label: '', preference_window_opens_at: today, preference_window_closes_at: '' });
  const [audience, setAudience] = useState('student'); const [scope, setScope] = useState('university'); const [schoolId, setSchoolId] = useState(''); const [departmentId, setDepartmentId] = useState(''); const [method, setMethod] = useState('existing'); const [search, setSearch] = useState(''); const [selected, setSelected] = useState([]); const [confirmAll, setConfirmAll] = useState(false); const [showRoster, setShowRoster] = useState(false);
  const selectedCycle = cycles.find((cycle) => cycle.id === cycleId) ?? null; const isDraft = selectedCycle?.status === 'not_started';
  // The top-right switcher is the primary way to choose work context. When a
  // Superadmin selects a Draft there, open its roster immediately instead of
  // making them choose the same cycle again on the generic first step.
  useEffect(() => {
    if (!cycleId && activeCycle?.status === 'not_started') { setCycleId(activeCycle.id); setStep(2); }
  }, [activeCycle?.id, activeCycle?.status, cycleId]);
  // Publishing is draft-only, but roster/document additions stay open for the
  // life of the cycle (new faculty joining, latecomer students) — only a
  // closed cycle is truly frozen.
  const canEditRoster = Boolean(selectedCycle) && selectedCycle.status !== 'closed';
  const { data: schools = [] } = useQuery({ queryKey: ['schools'], queryFn: () => api('/schools') }); const { data: departments = [] } = useQuery({ queryKey: ['departments'], queryFn: () => api('/departments') });
  const scopedDepartments = schoolId ? departments.filter((department) => department.school_id === schoolId) : [];
  const scopeValid = Boolean(scope === 'university' || (scope === 'school' && schoolId) || (scope === 'department' && departmentId));
  const scopeParams = new URLSearchParams({ participant_type: audience, scope, cycle_id: cycleId ?? '' }); if (schoolId) scopeParams.set('school_id', schoolId); if (departmentId) scopeParams.set('department_id', departmentId);
  const participants = useQuery({ queryKey: ['cycle-participants', cycleId], queryFn: () => api(`/cycles/${cycleId}/participants`), enabled: !!cycleId });
  const cycleDocuments = useQuery({ queryKey: ['cycle-documents', cycleId], queryFn: () => api(`/cycle-documents/${cycleId}`), enabled: !!cycleId });
  const allCount = useQuery({ queryKey: ['cycle-audience-count', cycleId, audience, scope, schoolId, departmentId], queryFn: () => api(`/cycles/people/count?${scopeParams}`), enabled: !!cycleId && canEditRoster && scopeValid });
  const people = useQuery({ queryKey: ['cycle-people', audience, scope, schoolId, departmentId, search], queryFn: () => api(`/cycles/people?${new URLSearchParams({ ...Object.fromEntries(scopeParams), q: search })}`), enabled: !!cycleId && canEditRoster && scopeValid && search.trim().length >= 2, retry: false });
  const selectedIds = useMemo(() => new Set(selected.map((person) => person.id)), [selected]); const studentCount = participants.data?.participants?.filter((row) => row.participant_type === 'student').length ?? 0; const facultyCount = participants.data?.participants?.filter((row) => row.participant_type === 'faculty').length ?? 0;
  const createCycle = useMutation({ mutationFn: () => api('/cycles', { method: 'POST', body: { ...draft, preference_window_opens_at: new Date(`${draft.preference_window_opens_at}T00:00:00`).toISOString(), preference_window_closes_at: draft.preference_window_closes_at ? new Date(`${draft.preference_window_closes_at}T23:59:59`).toISOString() : undefined } }), onSuccess: (cycle) => { queryClient.invalidateQueries({ queryKey: ['available-cycles'] }); setCycleId(cycle.id); setStep(2); } });
  const enrol = useMutation({ mutationFn: ({ type, ids, source = 'existing' }) => api(`/cycles/${cycleId}/participants`, { method: 'POST', body: { participant_type: type, user_ids: ids, source } }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['cycle-participants', cycleId] }); queryClient.invalidateQueries({ queryKey: ['cycle-audience-count'] }); setSelected([]); setSearch(''); } });
  const enrolAll = useMutation({ mutationFn: () => api(`/cycles/${cycleId}/participants/select-all`, { method: 'POST', body: { participant_type: audience, scope, school_id: schoolId || undefined, department_id: departmentId || undefined } }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['cycle-participants', cycleId] }); queryClient.invalidateQueries({ queryKey: ['cycle-audience-count'] }); setConfirmAll(false); } });
  const publish = useMutation({ mutationFn: () => api(`/cycles/${cycleId}/publish`, { method: 'POST' }), onSuccess: (cycle) => { queryClient.invalidateQueries({ queryKey: ['available-cycles'] }); selectCycle(cycle.id); } });
  const chooseCycle = (cycle) => { setCycleId(cycle.id); setStep(cycle.status === 'not_started' ? 2 : 3); };
  const resetScope = (next) => { setScope(next); setSchoolId(''); setDepartmentId(''); setSelected([]); setSearch(''); setConfirmAll(false); };
  const toggle = (person) => setSelected((current) => current.some((item) => item.id === person.id) ? current.filter((item) => item.id !== person.id) : [...current, person]);
  const addCreated = (user) => enrol.mutate({ type: user.roles?.[0]?.role, ids: [user.id] });
  const addImported = (rows) => ['student', 'faculty'].forEach((type) => { const ids = rows.filter((row) => row.ok && row.role === type).map((row) => row.id); if (ids.length) enrol.mutate({ type, ids, source: 'bulk_import' }); });
  const scopeName = scope === 'university' ? 'the university' : scope === 'school' ? schools.find((school) => school.id === schoolId)?.name : departments.find((department) => department.id === departmentId)?.name;

  return <div className="max-w-5xl"><PageHeader eyebrow="Cycle administration" title="Set up an internship cycle" description="Create the cycle, build one complete student/faculty roster using the existing hierarchy, then publish required documents." /><Stepper step={step} onStep={setStep} />
    {step === 1 && <Card className="p-6"><div className="max-w-2xl"><h2 className="text-xl font-bold">Cycle details</h2><p className="mt-1 text-sm text-slate-600">Organisation structure is already configured. This step only names the internship cycle and dates.</p><div className="mt-5 space-y-4"><div><Label>Cycle name</Label><Input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} placeholder="TF 2028 Internship Cycle" /></div><div><Label>Batch / cohort <span className="font-normal text-slate-400">(optional)</span></Label><Input value={draft.batch_label} onChange={(event) => setDraft({ ...draft, batch_label: event.target.value })} placeholder="For example: 2028 intake" /></div><div className="grid gap-3 sm:grid-cols-2"><div><Label>Opens</Label><Input type="date" value={draft.preference_window_opens_at} onChange={(event) => setDraft({ ...draft, preference_window_opens_at: event.target.value })} /></div><div><Label>Closes</Label><Input type="date" value={draft.preference_window_closes_at} onChange={(event) => setDraft({ ...draft, preference_window_closes_at: event.target.value })} /></div></div><Button onClick={() => createCycle.mutate()} disabled={!draft.name.trim() || createCycle.isPending}>{createCycle.isPending ? 'Creating…' : 'Build cycle roster'}</Button>{createCycle.isError && <p className="text-sm text-red-700">{createCycle.error.message}</p>}</div></div><div className="mt-6 border-t border-slate-100 pt-5"><h3 className="font-bold">Continue a cycle</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{cycles.map((cycle) => <button key={cycle.id} type="button" onClick={() => chooseCycle(cycle)} className="flex items-center justify-between rounded-lg border border-slate-200 px-3 py-3 text-left hover:border-indigo-300"><span><span className="block font-semibold">{cycle.name}</span><span className="text-xs text-slate-500">{cycle.batch_label || 'No batch label'}</span></span><Badge status={cycle.status === 'open' ? 'approved' : cycle.status === 'not_started' ? 'pending' : 'revoked'}>{statusLabel(cycle.status)}</Badge></button>)}</div></div></Card>}
    {step === 2 && (!selectedCycle ? <EmptyState title="Start with cycle details" description="Create a draft or choose one to build its roster." /> : !canEditRoster ? <Card className="p-6"><h2 className="text-xl font-bold">{selectedCycle.name}</h2><p className="mt-2 text-sm text-slate-600">This cycle is closed, so the roster is read-only.</p></Card> : <Card className="p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-indigo-600">Draft cycle</p><h2 className="mt-1 text-xl font-bold">Build roster for {selectedCycle.name}</h2><p className="mt-1 text-sm text-slate-600">Reuse people from any previous cycle or create new accounts in the selected department.</p></div><div className="flex gap-2"><Badge status="pending">{studentCount} students</Badge><Badge status="pending">{facultyCount} faculty</Badge></div></div>
      <div className="mt-5 rounded-xl bg-slate-50 p-4"><div className="grid gap-3 md:grid-cols-3"><div><Label>Audience</Label><Select value={audience} onChange={(event) => { setAudience(event.target.value); setSelected([]); setSearch(''); setConfirmAll(false); }}><option value="student">Students</option><option value="faculty">Faculty</option></Select></div><div><Label>Organisation scope</Label><Select value={scope} onChange={(event) => resetScope(event.target.value)}><option value="university">Entire university</option><option value="school">One school</option><option value="department">One department</option></Select></div>{scope !== 'university' && <div><Label>School</Label><Select value={schoolId} onChange={(event) => { setSchoolId(event.target.value); setDepartmentId(''); }}><option value="">Choose a school</option>{schools.map((school) => <option key={school.id} value={school.id}>{school.name}</option>)}</Select></div>}{scope === 'department' && <div><Label>Department</Label><Select value={departmentId} disabled={!schoolId} onChange={(event) => setDepartmentId(event.target.value)}><option value="">Choose a department</option>{scopedDepartments.map((department) => <option key={department.id} value={department.id}>{department.name}</option>)}</Select></div>}</div><p className="mt-3 text-sm text-slate-600">{scopeValid ? `Current scope: ${scopeName}.` : 'Choose the hierarchy level before adding people.'}</p></div>
      {scopeValid && <><div className="mt-5 grid gap-2 sm:grid-cols-3">{[['existing', 'Add existing people', 'Search or add all people in this scope.'], ['single', 'Create one account', 'Create and enrol one student or faculty member.'], ['bulk', 'Upload a department list', 'Create many accounts with temporary passwords.']].map(([id, title, description]) => <button key={id} type="button" onClick={() => setMethod(id)} disabled={id !== 'existing' && scope !== 'department'} className={`rounded-xl border p-4 text-left ${method === id ? 'border-indigo-500 bg-indigo-50 ring-2 ring-indigo-100' : 'border-slate-200 bg-white'} disabled:cursor-not-allowed disabled:opacity-50`}><p className="font-bold">{title}</p><p className="mt-1 text-sm text-slate-600">{description}</p>{id !== 'existing' && scope !== 'department' && <p className="mt-2 text-xs text-amber-700">Choose one department first.</p>}</button>)}</div>
        {scope !== 'department' && <div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4"><p className="font-semibold text-amber-950">Set up the organisation before building a roster</p><p className="mt-1 text-sm text-amber-900">Schools, departments, Deans, School Office users, HODs, and Faculty Coordinators are created in Organisation & Users. Once a department exists, return here to add students and faculty to this cycle.</p><Link to="/crcs/admin/users" className="mt-3 inline-flex rounded-lg bg-amber-700 px-3 py-2 text-sm font-bold text-white hover:bg-amber-800">Open Organisation & Users</Link></div>}
        {method === 'existing' && <div className="mt-5 rounded-xl border border-slate-200 p-5"><div className="flex flex-wrap items-end justify-between gap-3"><div className="min-w-64 flex-1"><Label>Find one or more existing {audience === 'student' ? 'students' : 'faculty members'}</Label><Input className="mt-1" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Name, email, or student roll number" /></div><Button variant="secondary" onClick={() => setConfirmAll(true)} disabled={!allCount.data?.count}>Add all {allCount.isLoading ? '…' : `${allCount.data?.count ?? 0} in scope`}</Button></div><p className="mt-2 text-xs text-slate-500">All-person actions are calculated on the server and require confirmation. Search returns up to 20 results.</p>{confirmAll && <div className="mt-4 rounded-lg border border-amber-300 bg-amber-50 p-4"><p className="font-semibold text-amber-950">Add {allCount.data?.count ?? 0} active {audience === 'student' ? 'students' : 'faculty members'} from {scopeName}?</p><p className="mt-1 text-sm text-amber-800">Already enrolled people are excluded. This changes the roster immediately.</p><div className="mt-3 flex gap-2"><Button onClick={() => enrolAll.mutate()} disabled={enrolAll.isPending}>{enrolAll.isPending ? 'Adding…' : 'Confirm and add all'}</Button><Button variant="secondary" onClick={() => setConfirmAll(false)}>Cancel</Button></div></div>}<div className="mt-4 max-h-64 overflow-y-auto rounded-lg bg-slate-50 p-2">{search.trim().length < 2 ? <p className="p-2 text-sm text-slate-500">Search for a specific person, or use the all-person action above.</p> : people.isLoading ? <p className="p-2 text-sm text-slate-500">Searching…</p> : people.data?.length ? people.data.map((person) => <label key={person.id} className="flex cursor-pointer items-center gap-3 rounded-md px-2 py-2 hover:bg-white"><input type="checkbox" checked={selectedIds.has(person.id)} onChange={() => toggle(person)} /><span><span className="block text-sm font-medium">{person.full_name}{person.roll_number ? ` · ${person.roll_number}` : ''}</span><span className="text-xs text-slate-500">{person.email}</span></span></label>) : <p className="p-2 text-sm text-slate-500">No matching active people in this scope.</p>}</div><div className="mt-3 flex items-center justify-between"><p className="text-sm text-slate-600">{selected.length} selected</p><Button onClick={() => enrol.mutate({ type: audience, ids: selected.map((person) => person.id) })} disabled={!selected.length || enrol.isPending}>{enrol.isPending ? 'Adding…' : 'Add selected'}</Button></div></div>}
        {method === 'single' && scope === 'department' && <CycleSinglePerson departmentId={departmentId} onComplete={addCreated} />}{method === 'bulk' && scope === 'department' && <CycleBulkImport departmentId={departmentId} onComplete={addImported} />}
      </>}{(enrol.isError || enrolAll.isError) && <p className="mt-3 text-sm text-red-700">{(enrol.error ?? enrolAll.error).message}</p>}<div className="mt-6 border-t border-slate-100 pt-5"><div className="flex items-center justify-between"><div><h3 className="font-bold">Roster review</h3><p className="text-sm text-slate-600">{studentCount} students and {facultyCount} faculty enrolled.</p></div><button type="button" className="text-sm font-bold text-indigo-700" onClick={() => setShowRoster(!showRoster)}>{showRoster ? 'Hide people' : 'View people'}</button></div>{showRoster && <div className="mt-3 grid gap-2 sm:grid-cols-2">{(participants.data?.participants ?? []).map((row) => <div key={row.id} className="rounded-lg bg-slate-50 px-3 py-2"><p className="text-sm font-semibold">{row.user?.full_name ?? 'Onboarded user'}</p><p className="text-xs text-slate-500">{row.participant_type}</p></div>)}</div>}</div><div className="mt-6 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-500">You can upload required PDFs now. Publishing stays unavailable until at least one student and one faculty member are enrolled.</p><Button onClick={() => setStep(3)}>Continue to required documents</Button></div></Card>)}
    {step === 3 && (!selectedCycle ? <EmptyState title="Start with a cycle" description="Create a draft before adding its required documents." /> : <Card className="p-6"><h2 className="text-xl font-bold">Required documents</h2><p className="mt-1 text-sm text-slate-600">Upload the cycle PDFs that every person must acknowledge before using a dashboard.</p><div className="mt-5 rounded-lg bg-slate-50 p-4"><p className="font-semibold">Roster: {studentCount} students · {facultyCount} faculty</p><p className="mt-1 text-sm text-slate-600">Publishing requires at least one student, one faculty member, and one required PDF.</p></div><RequiredDocuments cycleId={cycleId} isDraft={canEditRoster} documents={cycleDocuments.data?.documents} />{cycleDocuments.isError && <p className="mt-3 text-sm text-red-700">{cycleDocuments.error.message}</p>}{isDraft && <div className="mt-6 flex justify-end"><Button onClick={() => publish.mutate()} disabled={!studentCount || !facultyCount || !cycleDocuments.data?.documents?.some((document) => document.is_required) || publish.isPending}>{publish.isPending ? 'Publishing…' : 'Publish cycle'}</Button></div>}{publish.isError && <p className="mt-3 text-sm text-red-700">{publish.error.message}</p>}</Card>)}
  </div>;
}
